<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/10/8
 * Time: 15:32
 */

namespace common\widgets\mdeditor;


use common\helpers\ComHelper;
use common\helpers\UploadHelper;
use yii\base\Action;

/**
 * Class UploadAction
 * @package summer
 * @author 姜海强 <jhq0113@163.com>
 */
class UploadAction extends Action
{
    /**上传目录
     * @var
     * @author 姜海强 <jhq0113@163.com>
     */
    public $uploadPath;

    /**url前缀
     * @var
     * @author 姜海强 <jhq0113@163.com>
     */
    public $urlPrefix;

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->uploadPath = $this->uploadPath ? : \Yii::getAlias('@webroot/uploads');
        $this->urlPrefix  = $this->urlPrefix     ? : 'http://'.$_SERVER['HTTP_HOST'].'/uploads';
    }

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function run()
    {
        $file=UploadHelper::getFileByName('editormd-image-file');
        if(!$file)
        {
            exit(json_encode([
                'status'=>'404',
                'data'=>'请选择要上传的图片文件'
            ]));
        }

        $result = UploadHelper::upImg($file,$this->uploadPath,$this->urlPrefix);

        exit(json_encode([
            'success' => ($result['status'] === '200') ? 0 : 1,
            'message' => $result['data'],
            'url' => $result['data'],
        ]));
    }
}