<?php
/**
 * Created by PhpStorm.
 * User: Jiang Haiqiang
 * Date: 2018/11/2
 * Time: 下午11:21
 */

namespace common\widgets;

use yii\web\View;
use yii\helpers\Html;
use common\assets\BootstrapDatetimePickerAsset;
use yii\widgets\InputWidget;

/**
 * Class BootstrapDatetimePickerWidget
 * @package common\widgets
 * User Jiang Haiqiang
 */
class BootstrapDatetimePickerWidget extends InputWidget
{
    /**配置
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    public $datetimePickerOptions=[];

    /**默认日期格式
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    private $_defaultOptions=[
        //'format'            =>  'yyyy-mm-dd',
        'format'            =>  'yyyy-mm-dd hh:ii:ss',
        'autoclose'         =>  true,
        'todayHighlight'    =>  true,
        'language'          =>  'zh-CN',
        'showMeridian'      =>  true,
    ];

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //datetimePicker id
        $id = isset($this->datetimePickerOptions['id']) ? $this->datetimePickerOptions['id'] : Html::getInputId($this->model, $this->attribute);

        $this->setId($id);

        $this->datetimePickerOptions = array_merge($this->_defaultOptions,$this->datetimePickerOptions);
    }

    /**
     * @return string
     * @author 姜海强 <jhq0113@163.com>
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $this->registerAsset();

        return Html::activeTextInput($this->model, $this->attribute,[
            'id' => $this->id,
            'size'=>16,
            'class' => 'form-control'
        ]);

    }

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    protected function registerAsset()
    {
        $datetimePickerAssets = BootstrapDatetimePickerAsset::register($this->view);

        $script               = $datetimePickerAssets->dealOptionsAndGetScript($this->view,$this->id,$this->datetimePickerOptions);

        $this->view->registerJs($script, View::POS_READY);
    }
}