<?php
/**
 * Created by PhpStorm.
 * User: Jiang Haiqiang
 * Date: 2018/11/18
 * Time: 下午9:32
 */

namespace modules\cms;

/**
 * Class ActiveRecord
 * @package modules\cms
 * User Jiang Haiqiang
 */
class ActiveRecord extends \common\base\ActiveRecord
{
    /**
     * @return \yii\db\Connection
     * @author Jiang Haiqiang
     * @email  jhq0113@163.com
     */
    public static function getDb()
    {
        return parent::getDb(); // TODO: Change the autogenerated stub
    }
}